tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "universal-ctags/universal-ctags"

brew "asdf"
brew "bat"
brew "cmake"
brew "elixir"
brew "exercism"
brew "fd"
brew "fzf"
brew "gh"
brew "ghi"
brew "git"
brew "git-delta"
brew "grc"
brew "htop"
brew "hub"
brew "jq"
brew "lnav"
brew "mas"
brew "neovim"
brew "node"
brew "nodenv"
brew "openjdk"
brew "parallel"
brew "postgresql", restart_service: true
brew "procs"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rust"
brew "semgrep"
brew "spaceship"
brew "starship"
brew "stylua"
brew "subversion"
brew "switchaudio-osx"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "vim"
brew "vimpager"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "luarocks"

cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-source-sans-pro"
cask "font-jetbrains-mono"

mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
mas "Wipr", id: 1320666476
