gh extension install rsese/gh-actions-status       
gh extension install github/gh-autofix             
gh extension install mislav/gh-branch              
gh extension install davidraviv/gh-clean-branches  
gh extension install rnorth/gh-combine-prs         
gh extension install dlvhdr/gh-dash                
gh extension install schustafa/gh-pairing-with     
gh extension install seachicken/gh-poi             
gh extension install rneatherway/gh-slack          
