#! /usr/bin/env bash

# Check if a command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

echo "==> Upgrading gh extensions"
gh extension upgrade --all
echo ""

echo "==> Upgrading homebrew"
brew update && brew outdated && brew upgrade
echo ""

echo "===> Truncating lsp.log since it cannot auto-rotate"
truncate -s 0 ~/.local/state/nvim/lsp.log
echo ""
