# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 5000

# Disable the package module, hiding it from the prompt completely
[package]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[python]
symbol = " "

[lua]
symbol = " "

[golang]
symbol = "ﳑ "
disabled = true

[rust]
symbol = " "
disabled = true

[docker_context]
disabled = true

[ruby]
disabled = true

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
