prSections:
- title: My PRs
  filters: is:open assignee:@me
- title: Needs review
  filters: is:open review-requested:@me
- title: Involves me/team
  filters: is:open involves:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
  layout:
      creator:
        hidden: true
        # width: <number of columns>
        # grow: <bool> this will make the column grow in size
- title: Assigned
  filters: is:open assignee:@me
- title: Involves me/team
  filters: is:open involves:@me
defaults:
  preview:
    open: false
    width: 80
  prsLimit: 100
  issuesLimit: 100
  view: prs
  layout:
    prs:
      repo:
        grow: true,
        width: 20
        hidden: false
      creator:
        grow: true,
        width: 20
        hidden: false
    issues:
      repo:
        grow: true,
        width: 20
        hidden: false
      creator:
        grow: true,
        width: 20
        hidden: false
keybindings:
  prs: []
repoPaths: {}
theme:
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#89b4fa"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f38ba8"
      success: "#a6e3a1"
    background:
      selected: "#313244"
    border:
      primary: "#89b4fa"
      secondary: "#45475a"
      faint: "#313244"
